name: CI

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
