name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          python-version: '3.10' 
        
      - name: Install dependencies
        run: poetry install
        
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: '1.1.341'
          warnings: false